services:
  app:
    command: bun run start
    restart: always
    environment:
      - NODE_ENV=production

  redis:
    restart: always

  mysql:
    restart: always

  nginx:
    ports:
      - "80:80"
    restart: always
